theme: jekyll-theme-minimal

title: satvis
description: A simulation framework for generating labelled image data of satellite proximity operations.

show_downloads: true
logo: /assets/img/logo.png

github:
  zip_url: https://github.com/Ben-Guthrie/satvis/archive/refs/heads/master.zip
